### PR TITLE
Explain why fallback happened when subcommand is not supported, and fix rustdoc

### LINKED ISSUE #1341: Issue when building with `cross rustdoc`
Maintainers note: The issue was filed wrongly initially, the real issue is using `cross rustdoc`

### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When running 
```bash
cross +nightly-2023-07-16-aarch64-unknown-linux-gnu rustdoc --target=aarch64-unknown-linux-gnu -p bevy_asset@0.11.2  --  -Zunstable-options --output-format json
````
I get the following error:
```
[cross] warning: unable to get metadata for package
[cross] note: Falling back to `cargo` on the host.
qemu-aarch64: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory
```

If I use `+nightly-2023-07-16` by itself, it runs successfully but it fallbacks to cargo on host and the build clearly isn't being done on arm64.

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

0.2.5

### Example

_No response_

### Additional information / notes

_No response_

### PR DESCRIPTION
**Pull request by Emilgardis**
Resolves #1341 by adding rustdoc as a supported command. Also adds a explanation when a unsupported subcommand is used.

This also fixes a bug with `--list`

### CODE REVIEW

File: src/cli.rs [hunk 1]
```diff
@@ -55,7 +55,7 @@ pub fn fmt_subcommands(stdout: &str, msg_info: &mut MessageInfo) -> Result<()> {
     }
     if !host.is_empty() {
         msg_info.print("Host Commands:")?;
-        for line in &cross {
+        for line in &host {
```
Comment (Emilgardis) [inline src/cli.rs:58]: oops! :3
