### PR TITLE
Fix CMake Support and Enhance Newlib Targets

### LINKED ISSUE #1110: CMake cannot find NDK or toolchain file for Android
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I want to compile a dependency which is written in C and build it with CMake. The target is Android aarch64.
In order to do that, I specify in the build.rs file the Android (ANDROID_PLATFORM) and ABI (ANDROID_ABI) version, as requested from the official documentation: https://developer.android.com/ndk/guides/cmake#file
The CMAKE_TOOLCHAIN_FILE variable is not needed anymore, as CMake > 3.21 is used.
When I try to compile it with `cross build --target aarch64-linux-android` CMake cannot find the NDK or a standalone toolchain.

> --- stderr
> CMake Error at /usr/local/share/cmake-3.23/Modules/Platform/Android-Determine.cmake:209 (message):
>   Android: Neither the NDK or a standalone toolchain was found.

Looking at the environment variables I see that the needed variables for CMake are not set as requested here: https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android

My question is now, what is the best approach in order to built C/C++ dependencies with CMake for Android?

### What target(s) are you cross-compiling for?

aarch64-linux-android

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (a8082de 2022-10-26)

### Example

_No response_

### Additional information / notes

_No response_

### LINKED ISSUE #1113: Newlib Targets Incorrectly Report `std` Support in `targets.toml`.
Looking at [Rust Platform Support](https://doc.rust-lang.org/rustc/platform-support.html), we see:

target | std | notes
-- | -- | --
thumbv6m-none-eabi | * | Bare Cortex-M0, M0+, M1
thumbv7em-none-eabi | * | Bare Cortex-M4, M7
thumbv7em-none-eabihf | * | Bare Cortex-M4F, M7F, FPU, hardfloat
thumbv7m-none-eabi | * | Bare Cortex-M3

where:

> \* indicates the target only supports [no_std](https://rust-embedded.github.io/book/intro/no-std.html) development.

However, all of our targets for newlib report `std = true`.

https://github.com/cross-rs/cross/blob/35a1e174aeb7f4a81d26e7c2efba2aee63a42b6f/targets.toml#L440-L458

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Fix CMake Support and Enhance Newlib Targets

Fix CMake support for Android targets by providing a toolchain file that specifies the API level and the standalone toolchain path, and ensuring that compiler detection is forcibly disabled. Fix CMake support for newlib targets by providing a toolchain file that signals to CMake it is compiling for an embedded target, providing correct C, C++, and ASM flags even when invoked externally, and ensuring CMake skips testing if the C and C++ compilers work by running a binary file. Also add C++ support to bare-metal newlib targets, by also installing `libstdc++-arm-none-eabi-newlib`. Finally, `targets.toml` was updated to ensure newlib targets do not have `std` support.

Other minor changes including using the Cortex-M1 CPU for `thumbv6m-none-eabi` rather than the Cortex-M3 (an ARMv7-M CPU) for the Qemu runner.

To ensure these work, test suites for CMake using C+11 features, CMake's `try_run` feature (checking [CMAKE_CROSSCOMPILING_EMULATOR](https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING_EMULATOR.html) is set), and a `no_std` package with a C++ dependency have been added.

Closes #1110.
Closes #1113.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
Note that this isn't close to complete yet. This just adds the CMake unittests.
bors try

**Comment by Alexhuszagh** [comment]
bors try --target *android*

**Comment by Alexhuszagh** [comment]
bors try --target *android*

**Comment by Alexhuszagh** [comment]
This currently uses a `rust-cmake-hello-world` which won't work for `no_std` targets, so we really should have both a library and a binary, where CMake module just does a `no_std` calculation or something.

**Comment by Alexhuszagh** [comment]
I've fixed CMake support for Android and newlib here, as well as added C++ support for newlib.

bors try --target *android* --target *none*

File: ci/test.sh [hunk 1]
```diff
@@ -71,8 +71,6 @@ main() {
         popd
 
         rm -rf "${td}"
-
```
Comment (Alexhuszagh) [inline ci/test.sh:74]: We now want to run the CMake tests as well.

File: ci/test.sh [hunk 2]
```diff
@@ -166,7 +164,7 @@ main() {
     fi
 
     # Test C++ support
-    if (( ${CPP:-0} )); then
+    if (( ${STD:-0} )) && (( ${CPP:-0} )); then
```
Comment (Alexhuszagh) [inline ci/test.sh:167]: This assumes we have C++ and std support, so we have to make that explicit.

File: ci/test.sh [hunk 3]
```diff
@@ -197,6 +195,22 @@ main() {
...
     fi
+
+    # tst cmake support
+    td="$(mkcargotemp -d)"
+
+    git clone --depth 1 https://github.com/cross-rs/rust-cmake-hello-world "${td}"
+
+    pushd "${td}"
+    retry cargo fetch
+    if (( ${STD:-0} )) && (( ${RUN:-0} )); then
```
Comment (Alexhuszagh) [inline ci/test.sh:206]: The `rust-cmake-hello-world` has both a `no_std` lib and a `std` binary, so we can check support for either/or.

File: docker/Dockerfile.thumbv6m-none-eabi [hunk 4]
```diff
@@ -10,14 +10,22 @@ RUN /cmake.sh
 COPY xargo.sh /
 RUN /xargo.sh
 
-COPY qemu.sh /
 RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
     gcc-arm-none-eabi \
-    libnewlib-arm-none-eabi && \
-    /qemu.sh arm
+    libnewlib-arm-none-eabi \
+    libstdc++-arm-none-eabi-newlib
```
Comment (Alexhuszagh) [inline docker/Dockerfile.thumbv6m-none-eabi:16]: These targets actually support C++, and `gcc-arm-none-eabi` actually contains the C++ compiler, just not `libstdc++v3`. If we install that, these targets support C++ just fine.

File: docker/Dockerfile.thumbv6m-none-eabi [hunk 5]
```diff
@@ -10,14 +10,22 @@ RUN /cmake.sh
...
+
+COPY qemu.sh /
+RUN /qemu.sh arm
+
+COPY newlib.cmake /opt/newlib.cmake
+ENV CMAKE_TOOLCHAIN_FILE=/opt/newlib.cmake
+ENV CROSS_NEWLIB_OBJECT_FLAGS="-ffunction-sections -fdata-sections -mthumb -march=armv6s-m"
 
-ENV QEMU_CPU=cortex-m3 \
+ENV QEMU_CPU=cortex-m1 \
```
Comment (Alexhuszagh) [inline docker/Dockerfile.thumbv6m-none-eabi:25]: `cortex-m3` is an ARMv7-M target, `cortex-m1` is the proper CPU here for ARMv6-M (see [ARM Cortex-M](https://en.wikipedia.org/wiki/ARM_Cortex-M#Cortex-M1)).

File: docker/Dockerfile.thumbv6m-none-eabi [hunk 6]
```diff
@@ -10,14 +10,22 @@ RUN /cmake.sh
...
-    /qemu.sh arm
+    libnewlib-arm-none-eabi \
+    libstdc++-arm-none-eabi-newlib
+
+COPY qemu.sh /
+RUN /qemu.sh arm
+
+COPY newlib.cmake /opt/newlib.cmake
+ENV CMAKE_TOOLCHAIN_FILE=/opt/newlib.cmake
+ENV CROSS_NEWLIB_OBJECT_FLAGS="-ffunction-sections -fdata-sections -mthumb -march=armv6s-m"
```
Comment (Alexhuszagh) [inline docker/Dockerfile.thumbv6m-none-eabi:23]: See `newlib.cmake` below for why these defaults are provided.

File: docker/android.cmake [hunk 7]
```diff
@@ -0,0 +1,33 @@
+# toolchain file for android targets, see #1110
+
+set(CMAKE_SYSTEM_NAME Android)
+set(CMAKE_SYSTEM_PROCESSOR "$ENV{CROSS_ANDROID_ARCH}")
```
Comment (Alexhuszagh) [inline docker/android.cmake:4]: This is not the same as the arch elsewhere: it must be `i686`, `aarch64`, `x86_64`, `armv7-a`, or `armv5te`. Just setting `arm` will not work.

File: docker/android.cmake [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+set(CMAKE_ANDROID_STANDALONE_TOOLCHAIN /android-ndk)
+set(CMAKE_ANDROID_API "$ENV{CROSS_ANDROID_SDK}")
```
Comment (Alexhuszagh) [inline docker/android.cmake:6]: We can't auto-detect the Android API, so we manually set it. CMake will still warn about this, but it's irrelevant since it's manually set.

File: docker/android.cmake [hunk 9]
```diff
@@ -0,0 +1,33 @@
+# toolchain file for android targets, see #1110
+
+set(CMAKE_SYSTEM_NAME Android)
+set(CMAKE_SYSTEM_PROCESSOR "$ENV{CROSS_ANDROID_ARCH}")
+set(CMAKE_ANDROID_STANDALONE_TOOLCHAIN /android-ndk)
```
Comment (Alexhuszagh) [inline docker/android.cmake:5]: Since we use a standalone Android NDK with the `/android-ndk/sysroot` with no version prefix, we need to use `CMAKE_ANDROID_STANDALONE_TOOLCHAIN ` and not `CMAKE_SYSROOT` nor `CMAKE_ANDROID_NDK`.

See the docs [here](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android).

File: docker/android.cmake [hunk 10]
```diff
@@ -0,0 +1,33 @@
...
+set(CMAKE_ANDROID_API "$ENV{CROSS_ANDROID_SDK}")
+
+# not all of these are standard, however, they're common enough
+# that it's good practice to define them.
+set(prefix "$ENV{CROSS_ANDROID_TARGET}")
+set(CMAKE_C_COMPILER "${prefix}-gcc")
```
Comment (Alexhuszagh) [inline docker/android.cmake:11]: Only `CMAKE_AR`, `CMAKE_RANLIB`, `CMAKE_C_COMPILER`, `CMAKE_ASM_COMPILER`, and `CMAKE_CXX_COMPILER` are standard, however, other tools will often use values provided by those variables even though they're not standard. Many toolchain files will provide them.

File: docker/android.cmake [hunk 11]
```diff
@@ -0,0 +1,33 @@
...
+
+# required because otherwise it tries to detect compiler features
+# from `/android-ndk/bin/clang`, which fails. these macros are
+# technically deprecated, but required for proper function
+include(CMakeForceCompiler)
+set(CMAKE_WARN_DEPRECATED FALSE)
+CMAKE_FORCE_C_COMPILER("${CMAKE_C_COMPILER}" GNU)
+CMAKE_FORCE_CXX_COMPILER("${CMAKE_CXX_COMPILER}" GNU)
+
+set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
```
Comment (Alexhuszagh) [inline docker/android.cmake:30]: Standard for cross-compiling.

File: docker/newlib.cmake [hunk 12]
```diff
@@ -0,0 +1,35 @@
+# toolchain file for newlib targets, see #1110
+
+# if we don't set generic, it tries to test the compiler which fails
```
Comment (Alexhuszagh) [inline docker/newlib.cmake:3]: This comment needs to be changed: if we don't set it to generic, it will complain the system is unknown.

File: targets.toml [hunk 13]
```diff
@@ -440,22 +440,26 @@ std = true
 [[target]]
 target = "thumbv6m-none-eabi"
 os = "ubuntu-latest"
-std = true
```
Comment (Alexhuszagh) [inline targets.toml:443]: All these targets do not support `std`, but they do now support C++.

**Comment by Alexhuszagh** [comment]
bors try --target *android* --target *none*
This should be ready for review now.

File: ci/test.sh [hunk 14]
```diff
@@ -197,6 +209,22 @@ main() {
 
         rm -rf "${td}"
     fi
+
+    # tst cmake support
```
Comment (Emilgardis) [inline ci/test.sh:213]: typo

**Review by Emilgardis — APPROVED** [review]

**Comment by Alexhuszagh** [comment]
This still has minor issues, and I'm currently testing it with more complex projects:
https://github.com/Alexhuszagh/rust-re2

**Comment by eli-schwartz** [comment]
> and Meson itself tries to entirely recreate the [Rust build system](https://mesonbuild.com/Rust.html) which is absolutely cursed

Alas, we live in a world where cargo doesn't really seem to want to provide a (working) build plan, see e.g. https://github.com/rust-lang/cargo/issues/7614. You should see how "absolutely cursed" bazel's solution to the same problem is. ;)

If and when Rust decides this is an interesting problem to solve for real in a non "so unstable we need to delete it" way, you can be sure literally everyone trying to integrate rust into multi-language build systems of a wide variety of descriptions, will be delighted to know. :p

File: docker/android.cmake (hunk 10 above)
Comment (Alexhuszagh) [reply docker/android.cmake]: It turns out setting these manually for the `CMAKE_ASM_COMPILER`, etc., fails badly with downstream configurations. See https://github.com/cross-rs/cross/issues/1110#issuecomment-1303781124.

**Comment by Alexhuszagh** [comment]
I think I've fixed Android support with more complex targets:
bors try --target *android* --target *none*

**Comment by Alexhuszagh** [comment]
This is currently failing due to missing locks on Android ARMv5te, which isn't supported by newer [NDKs](https://developer.android.com/ndk/guides/abis) anyway:

> Note: Historically the NDK supported ARMv5 (armeabi), and 32-bit and 64-bit MIPS, but support for these ABIs was removed in NDK r17.

It's probably just worth disabling the `re2` test for that platform specifically. `__libcpp_signed_lock_free` isn't present in `libc++_shared.so` for `arm-linux-androideabi`.

**Comment by Alexhuszagh** [comment]
bors try --target *android* --target *none*

File: ci/test.sh [hunk 15]
```diff
@@ -197,6 +209,29 @@ main() {
...
+
+    git clone \
+        --recursive \
+        --depth 1 \
+        https://github.com/cross-rs/rust-cmake-hello-world "${td}"
+
+    pushd "${td}"
+    retry cargo fetch
+    if [[ "${TARGET}" == "arm-linux-androideabi" ]]; then
+        # ARMv5te isn't supported anymore by Android, which produces missing
```
Comment (Alexhuszagh) [inline ci/test.sh:224]: `re2` might not be supported on some other platforms without native atomics, it's probably better to allow-list certain architectures.

**Comment by Alexhuszagh** [comment]
bors try

File: ci/test.sh (hunk 15 above)
Comment (Alexhuszagh) [reply ci/test.sh:224]: Looks like there's numerous linking issues with every musl target, likely due to a lack of locale support, but also including much more than just that. Missing symbols include:
- `__extendsftf2`
- `floor`
- `wmemcpy`
- `pthread_mutex_unlock`
- `setlocale`

Which is some soft-float intrinsics, wide character support, pthreads, and locale functions.

Comment (Alexhuszagh) [reply ci/test.sh:224]: Looks like the Windows GNU target issues are not our fault: re2 requires C++17 support for [shared_mutex](https://en.cppreference.com/w/cpp/thread/shared_mutex) while only providing flags for C++11 support. Let's see if we can go to an older re2 version...

https://github.com/google/re2/blob/7a65faf439295e941baa6640a717d89c1f13e9cd/CMakeLists.txt#L80-L84

Comment (Alexhuszagh) [reply ci/test.sh:224]: Another issue: the package we install on Ubuntu 20.04 doesn't support `std::thread`, since we have no thread support. We'll likely want to upgrade to Ubuntu 22.04 for the Windows GNU targets.

Comment (Alexhuszagh) [reply ci/test.sh:224]: x86_64 CentOS doesn't have `int32_t`... ok.
https://github.com/cross-rs/cross/actions/runs/3406755182/jobs/5665741079#step:12:2303

Comment (Alexhuszagh) [reply ci/test.sh:224]: For sufficiently-complex musl targets, it seems we need to either link to dynamic libstdc++ (see #902), or we can always link to libc (which will only provide missing symbols for the C runtime).

Adding `RUSTFLAGS="-C link-arg=-lc"` fixes the issue. @Emilgardis  thoughts on the best solution? Always link to libc, or revert #902, knowing that the latter will fail with a lot of targets? I think the latter is probably preferable, but it would require a custom musl linker that always adds `-lc`.

**Comment by Alexhuszagh** [comment]
bors try
This still should be failing on musl and Windows GNU, however, the CentOS builds should now be fixed.

**Comment by Alexhuszagh** [comment]
We should also probably set `CMAKE_CROSSCOMPILING_EMULATOR` as described here https://github.com/cross-rs/cross/issues/1110#issuecomment-1305590929.

**Comment by Alexhuszagh** [comment]
I'm going to mark this as a draft until #1118, #1123, and #1125 are merged, since it will be easier to build upon them rather than the inverse.

File: docker/toolchain.cmake [hunk 16]
```diff
@@ -0,0 +1,57 @@
...
+set(CMAKE_OBJCOPY "${prefix}objcopy")
+set(CMAKE_OBJDUMP "${prefix}objdump")
+set(CMAKE_RANLIB "${prefix}ranlib")
+set(CMAKE_STRIP "${prefix}strip")
+
+# these are cached so any build system that compiled outside of the rust
+# build system, such as a third-party cmake build and install of a shared
+# library, will still work. however, cmake-rs can override these values
+if(DEFINED ENV{CROSS_CMAKE_OBJECT_FLAGS})
+    set(CMAKE_C_FLAGS "$ENV{CROSS_CMAKE_OBJECT_FLAGS}" CACHE INTERNAL "C Compiler options")
```
Comment (Alexhuszagh) [inline docker/toolchain.cmake:32]: We cache these internally so `cmake-rs` can overwrite them.

File: docker/toolchain.cmake [hunk 17]
```diff
@@ -0,0 +1,57 @@
...
+    set(CMAKE_CXX_FLAGS "$ENV{CROSS_CMAKE_OBJECT_FLAGS}" CACHE INTERNAL "C++ Compiler options")
+    set(CMAKE_ASM_FLAGS "$ENV{CROSS_CMAKE_OBJECT_FLAGS}" CACHE INTERNAL "ASM Compiler options")
+endif()
+
+# if cross-compiling, we need to disable where the root path
+# is found and also provide our own sysroot
+set(native ENV{CROSS_CMAKE_NATIVE})
```
Comment (Alexhuszagh) [inline docker/toolchain.cmake:39]: This can be removed, since the native Dockerfiles don't actually use a custom toolchain file.

File: docker/Dockerfile.aarch64-linux-android [hunk 18]
```diff
@@ -34,15 +34,21 @@ RUN /android-system.sh arm64
...
 ENV CROSS_SYSROOT=/android-ndk/sysroot
+ENV CROSS_ANDROID_SDK=$ANDROID_SDK
 COPY android-symlink.sh /
 RUN /android-symlink.sh aarch64 aarch64-linux-android
 
 COPY android-runner /
 
+COPY android.cmake /opt/android.cmake
+ENV CMAKE_TOOLCHAIN_FILE=/opt/android.cmake
+ENV CROSS_CMAKE_OBJECT_FLAGS="-DANDROID -ffunction-sections -fdata-sections -fPIC"
```
Comment (Alexhuszagh) [inline docker/Dockerfile.aarch64-linux-android:45]: All of the `CROSS_CMAKE_OBJECT_FLAGS` were generated manually by checking a project using CMake that failed and output the `CMAKE_C_FLAGS`, etc., and confirmed the C, C++, and ASM flags were all the same.

File: docker/Dockerfile.aarch64-linux-android [hunk 19]
```diff
@@ -34,15 +34,21 @@ RUN /android-system.sh arm64
...
+
 # Libz is distributed in the android ndk, but for some unknown reason it is not
 # found in the build process of some crates, so we explicit set the DEP_Z_ROOT
+ENV CROSS_TARGET_RUNNER="/android-runner aarch64"
```
Comment (Alexhuszagh) [inline docker/Dockerfile.aarch64-linux-android:49]: This allows us to use it both for the cargo runner and for `CMAKE_CROSSCOMPILING_EMULATOR`, which is required when using `try_run` in some CMake build systems.

File: docker/Dockerfile.aarch64-linux-android [hunk 20]
```diff
@@ -63,4 +69,7 @@ ENV CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
     TMPDIR=/tmp/ \
     ANDROID_DATA=/ \
     ANDROID_DNS_MODE=local \
-    ANDROID_ROOT=/system
+    ANDROID_ROOT=/system \
+    CROSS_CMAKE_SYSTEM_NAME=Android \
+    CROSS_CMAKE_SYSTEM_PROCESSOR=aarch64 \
+    CROSS_CMAKE_CRT=android
```
Comment (Alexhuszagh) [inline docker/Dockerfile.aarch64-linux-android:75]: `CROSS_CMAKE_CRT` is technically not needed for this: it's only needed for `newlib` and we could probably do `CROSS_CMAKE_NEWLIB` but I figured it might be nice just to have this. It might be better to check for `*-none-*` though since we only use it to check if we should build an executable or staticlib when testing if the compiler works.

File: docker/Dockerfile.aarch64-linux-android [hunk 21]
```diff
@@ -63,4 +69,7 @@ ENV CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
     TMPDIR=/tmp/ \
     ANDROID_DATA=/ \
     ANDROID_DNS_MODE=local \
-    ANDROID_ROOT=/system
+    ANDROID_ROOT=/system \
+    CROSS_CMAKE_SYSTEM_NAME=Android \
+    CROSS_CMAKE_SYSTEM_PROCESSOR=aarch64 \
```
Comment (Alexhuszagh) [inline docker/Dockerfile.aarch64-linux-android:74]: `CROSS_CMAKE_SYSTEM_PROCESSOR` is required for `CMAKE_SYSTEM_PROCESSOR` and `CROSS_CMAKE_SYSTEM_NAME` is just provided for consistency with every other toolchain.

File: docker/Dockerfile.aarch64-unknown-linux-gnu [hunk 22]
```diff
@@ -30,13 +30,21 @@ RUN /linux-image.sh aarch64
 
 COPY linux-runner base-runner.sh /
 
+COPY toolchain.cmake /opt/toolchain.cmake
+ENV CMAKE_TOOLCHAIN_FILE=/opt/toolchain.cmake
```
Comment (Alexhuszagh) [inline docker/Dockerfile.aarch64-unknown-linux-gnu:34]: We can use a single CMake toolchain file for every target besides Android. The `CROSS_CMAKE_OBJECT_FLAGS` are provided so the same flags are used by default when CMake is used outside of `cmake-rs`, for whatever reason. `cmake-rs` will override these, so it's not a major deal.

File: docker/toolchain.cmake [hunk 23]
```diff
@@ -0,0 +1,57 @@
...
+# required so CMAKE_CROSSCOMPILING_EMULATOR is set,
+# as well for embedded systems and other targets.
+#
+# all embedded systems without an OS should set the system name to generic
+# https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html
+
+set(CMAKE_SYSTEM_NAME "$ENV{CROSS_CMAKE_SYSTEM_NAME}")
+set(CMAKE_SYSTEM_PROCESSOR "$ENV{CROSS_CMAKE_SYSTEM_PROCESSOR}")
+if(DEFINED ENV{CROSS_TARGET_RUNNER})
+    set(CMAKE_CROSSCOMPILING_EMULATOR $ENV{CROSS_TARGET_RUNNER})
```
Comment (Alexhuszagh) [inline docker/toolchain.cmake:11]: Not all targets have runners, disable it if they don't.

File: docker/Dockerfile.x86_64-unknown-netbsd [hunk 24]
```diff
@@ -13,10 +13,17 @@ RUN /xargo.sh
...
 ENV CROSS_SYSROOT=/usr/local/x86_64-unknown-netbsd
 ENV CARGO_TARGET_X86_64_UNKNOWN_NETBSD_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
     AR_x86_64_unknown_netbsd="$CROSS_TOOLCHAIN_PREFIX"ar \
     CC_x86_64_unknown_netbsd="$CROSS_TOOLCHAIN_PREFIX"gcc \
     CXX_x86_64_unknown_netbsd="$CROSS_TOOLCHAIN_PREFIX"g++ \
-    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_netbsd="--sysroot=$CROSS_SYSROOT"
+    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_netbsd="--sysroot=$CROSS_SYSROOT" \
+    CROSS_CMAKE_SYSTEM_NAME=NetBSD \
+    CROSS_CMAKE_SYSTEM_PROCESSOR=x86_64 \
+    CROSS_CMAKE_CRT=netbsd
```
Comment (Alexhuszagh) [inline docker/Dockerfile.x86_64-unknown-netbsd:29]: All of the BSDs use their own `libc` variants, so I've given them all different names.

File: docker/Dockerfile.x86_64-unknown-linux-gnu.centos [hunk 25]
```diff
@@ -26,6 +26,9 @@ COPY --from=0 /qemu /qemu
 
 COPY linux-runner base-runner.sh /
 
+# NOTE: this target is only supported on linux/amd64 hosts,
```
Comment (Alexhuszagh) [inline docker/Dockerfile.x86_64-unknown-linux-gnu.centos:29]: I think we can actually remove this file since it's never used if `native.centos` is used instead.

File: docker/Dockerfile.x86_64-unknown-illumos [hunk 26]
```diff
@@ -12,11 +12,18 @@ RUN /xargo.sh
...
 ENV PATH=$PATH:/usr/local/x86_64-unknown-illumos/bin/ \
     CARGO_TARGET_X86_64_UNKNOWN_ILLUMOS_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
     AR_x86_64_unknown_illumos="$CROSS_TOOLCHAIN_PREFIX"ar \
     CC_x86_64_unknown_illumos="$CROSS_TOOLCHAIN_PREFIX"gcc \
     CXX_x86_64_unknown_illumos="$CROSS_TOOLCHAIN_PREFIX"g++ \
-    BINDGEN_EXTRA_CLANG_ARGS_sparcv9_sun_solaris="--sysroot=$CROSS_SYSROOT"
+    BINDGEN_EXTRA_CLANG_ARGS_sparcv9_sun_solaris="--sysroot=$CROSS_SYSROOT" \
+    CROSS_CMAKE_SYSTEM_NAME=illumos \
+    CROSS_CMAKE_SYSTEM_PROCESSOR=x86_64 \
+    CROSS_CMAKE_CRT=solaris
```
Comment (Alexhuszagh) [inline docker/Dockerfile.x86_64-unknown-illumos:29]: Illumos and Solaris are very similar, so I gave it the same CRT name.

File: docker/Dockerfile.wasm32-unknown-emscripten [hunk 27]
```diff
@@ -17,5 +17,7 @@ RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
 
 ENV CROSS_TOOLCHAIN_PREFIX=em
 ENV CROSS_SYSROOT=/emsdk/upstream/emscripten/cache/sysroot
-ENV CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_RUNNER=node \
-    BINDGEN_EXTRA_CLANG_ARGS_wasm32_unknown_emscripten="--sysroot=$CROSS_SYSROOT"
+ENV CROSS_TARGET_RUNNER="node"
+ENV CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_RUNNER="$CROSS_TARGET_RUNNER" \
+    BINDGEN_EXTRA_CLANG_ARGS_wasm32_unknown_emscripten="--sysroot=$CROSS_SYSROOT" \
+    CMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
```
Comment (Alexhuszagh) [inline docker/Dockerfile.wasm32-unknown-emscripten:23]: wasm32 and asmjs provide their own CMake toolchain files.

File: docker/Dockerfile.wasm32-unknown-emscripten [hunk 28]
```diff
@@ -17,5 +17,7 @@ RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
 
 ENV CROSS_TOOLCHAIN_PREFIX=em
 ENV CROSS_SYSROOT=/emsdk/upstream/emscripten/cache/sysroot
-ENV CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_RUNNER=node \
-    BINDGEN_EXTRA_CLANG_ARGS_wasm32_unknown_emscripten="--sysroot=$CROSS_SYSROOT"
+ENV CROSS_TARGET_RUNNER="node"
```
Comment (Alexhuszagh) [inline docker/Dockerfile.wasm32-unknown-emscripten:20]: We could possibly provide the additional pthread flags to the runner. See:
https://github.com/emscripten-core/emscripten/blob/e9ba3598df8f219b8c9c505c4ed1ed4618001123/emcmake.py#L44

File: docker/Dockerfile.thumbv7m-none-eabi [hunk 29]
```diff
@@ -10,15 +10,26 @@ RUN /cmake.sh
...
+
+COPY qemu.sh /
+RUN /qemu.sh arm
+
+COPY toolchain.cmake /opt/toolchain.cmake
+ENV CMAKE_TOOLCHAIN_FILE=/opt/toolchain.cmake
+ENV CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -mthumb -march=armv7-m"
 
 ENV CROSS_TOOLCHAIN_PREFIX=arm-none-eabi-
+ENV CROSS_SYSROOT="/usr/lib/arm-none-eabi"
```
Comment (Alexhuszagh) [inline docker/Dockerfile.thumbv7m-none-eabi:26]: The THUMB newlib targets include their own binutils and include headers under this directory, so it's effectively a sysroot for most intents and purposes.

**Comment by Alexhuszagh** [comment]
bors try

**Comment by Alexhuszagh** [comment]
bors try-

**Comment by Alexhuszagh** [comment]
bors try

**Comment by Alexhuszagh** [comment]
bors try *bsd

**Comment by Alexhuszagh** [comment]
bors try --target *bsd

**Comment by Alexhuszagh** [comment]
bors try

**Comment by Alexhuszagh** [comment]
We can actually make these changes interface less with the image: `CMAKE_TOOLCHAIN_FILE_thumbv6m_none_eabi` for example, can be provided, which `cmake-rs` will look at first.

**Comment by Alexhuszagh** [comment]
bors try --target x86_64-unknown-dragonfly

**Comment by Alexhuszagh** [comment]
bors try --target x86_64-unknown-dragonfly

File: docker/Dockerfile.i686-pc-windows-gnu [hunk 30]
```diff
@@ -34,12 +34,20 @@ RUN mkdir -p /usr/lib/binfmt-support/ && \
...
 ENV CROSS_SYSROOT=/usr/i686-w64-mingw32
+ENV CROSS_TARGET_RUNNER="wine"
 ENV CARGO_TARGET_I686_PC_WINDOWS_GNU_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc-posix \
-    CARGO_TARGET_I686_PC_WINDOWS_GNU_RUNNER=wine \
+    CARGO_TARGET_I686_PC_WINDOWS_GNU_RUNNER="$CROSS_TARGET_RUNNER" \
     CC_i686_pc_windows_gnu="$CROSS_TOOLCHAIN_PREFIX"gcc-posix \
     CXX_i686_pc_windows_gnu="$CROSS_TOOLCHAIN_PREFIX"g++-posix \
-    BINDGEN_EXTRA_CLANG_ARGS_i686_pc_windows_gnu="--sysroot=$CROSS_SYSROOT"
+    BINDGEN_EXTRA_CLANG_ARGS_i686_pc_windows_gnu="--sysroot=$CROSS_SYSROOT" \
+    CROSS_CMAKE_SYSTEM_NAME=Windows \
```
Comment (Alexhuszagh) [inline docker/Dockerfile.i686-pc-windows-gnu:51]: For some reason, `cmake-rs` passes this as `windows` only for 32-bit Windows GNU but the correct value is `Windows`, and `Platform/windows` is unknown to CMake. So, this differs **slightly** from cmake-rs.

**Comment by Alexhuszagh** [comment]
bors try --target *pc-windows-gnu

**Comment by Alexhuszagh** [comment]
bors try --target *none*

File: docker/toolchain.cmake [hunk 31]
```diff
@@ -0,0 +1,56 @@
...
+if(DEFINED ENV{CROSS_TARGET_RUNNER})
+    set(runner "$ENV{CROSS_TARGET_RUNNER}")
+    separate_arguments(runner)
+    set(CMAKE_CROSSCOMPILING_EMULATOR ${runner})
+endif()
+
+# not all of these are standard, however, they're common enough
+# that it's good practice to define them.
+set(prefix "$ENV{CROSS_TOOLCHAIN_PREFIX}")
+set(CMAKE_C_COMPILER "${prefix}gcc")
```
Comment (Alexhuszagh) [inline docker/toolchain.cmake:19]: This needs a suffix if we're using Windows for the `*posix` variants.

**Comment by Alexhuszagh** [comment]
bors try --target *pc-windows-gnu

**Comment by Alexhuszagh** [comment]
bors try
This should pass for all but the MIPS64 musl targets.

**Comment by Alexhuszagh** [comment]
Everything should be fixed. I'm going to roll out the final musl patches to a separate PR, and then fix all the toolchain file names to ensure they're target specific, and this PR is ready.

bors try

**Comment by Alexhuszagh** [comment]
bors try

File: docker/Dockerfile.armv7-linux-androideabi [hunk 32]
```diff
@@ -56,11 +59,16 @@ ENV CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
...
     HOME=/tmp/ \
     TMPDIR=/tmp/ \
     ANDROID_DATA=/ \
     ANDROID_DNS_MODE=local \
-    ANDROID_ROOT=/system
+    ANDROID_ROOT=/system \
+    CROSS_CMAKE_SYSTEM_NAME=Android \
+    CROSS_CMAKE_SYSTEM_PROCESSOR=armv7-a \
+    CROSS_CMAKE_CRT=android \
+    CROSS_CMAKE_OBJECT_FLAGS="--target=arm-linux-androideabi -DANDROID -ffunction-sections -fdata-sections -fPIC --target=armv7-linux-androideabi"
```
Comment (Alexhuszagh) [inline docker/Dockerfile.armv7-linux-androideabi:74]: I believe this change is correct, with `--target` provided twice, since that's what `cmake-rs` does as of `0.1.49` and `cc-rs` as of `1.0.77` (this is using Rust 1.64.0).

**Comment by Alexhuszagh** [comment]
bors try

**Comment by Alexhuszagh** [comment]
bors try

**Review by Emilgardis — APPROVED** [review]
lgtm

**Comment by Alexhuszagh** [comment]
bors r=Emilgardis
