### PR TITLE
Fix remote docker paths on Windows hosts.

### LINKED ISSUE #1081: Cross Data Volume Fails On Windows Host
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When attempting to create a persistent data volume on the `Z:` drive

```bash
cross-util volumes create --toolchain stable-x86_64-unknown-linux-gnu --verbose
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe"
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" version -f '{{ .Server.Os }},,,{{ .Server.Arch }}'
+ rustc --print sysroot
+ rustc --print target-list
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" volume inspect cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" volume create cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5
cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" ps -a --filter 'name=cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276' --format {{.State}}
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" run --name cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276 --rm -v cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5:/cross -d -t ubuntu:20.04
475fa58af612e8d06663003d7020f2b273585a2c5c9d4308902905611e8aca2f
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276 sh -c 'mkdir -p '\''/mnt/z/cross/mnt/c/Users/ahusz'\'''
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.xargo' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.xargo
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276 sh -c 'mkdir -p '\''/mnt/z/cross/mnt/c/Users/ahusz/.cargo'\'''
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.cargo\bin' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.cargo
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276 sh -c 'mkdir -p '\''/mnt/z/cross/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib'\'''
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu\bin' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu\libexec' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu\etc' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
```

It prefixes the drive with the `/mnt/z` prefix (which then is present before the initial `/mnt/c` prefix, so we get `/mnt/z/cross/mnt/c`, which prevents the mounted toolchains and packages from being found. Additionally, attempting to change to the correct working directory fails.

### What target(s) are you cross-compiling for?

_No response_

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [X] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (b789e46 2022-10-07)

### Example

A failing example. Here we create the persistent data volume on the Z drive, then attempt to run it on the C drive. This causes the toolchain to not be found.

```bash
$ cross-util volumes create --toolchain stable-x86_64-unknown-linux-gnu --verbose
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe"
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" version -f '{{ .Server.Os }},,,{{ .Server.Arch }}'
+ rustc --print sysroot
+ rustc --print target-list
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" volume inspect cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" volume create cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5
cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" ps -a --filter 'name=cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276' --format {{.State}}
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" run --name cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276 --rm -v cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5:/cross -d -t ubuntu:20.04
475fa58af612e8d06663003d7020f2b273585a2c5c9d4308902905611e8aca2f
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276 sh -c 'mkdir -p '\''/mnt/z/cross/mnt/c/Users/ahusz'\'''
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.xargo' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.xargo
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276 sh -c 'mkdir -p '\''/mnt/z/cross/mnt/c/Users/ahusz/.cargo'\'''
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.cargo\bin' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.cargo
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276 sh -c 'mkdir -p '\''/mnt/z/cross/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib'\'''
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu\bin' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu\libexec' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" cp -a 'C:\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu\etc' cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108312276:/mnt/z/cross/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
# on the Z: drive
$ CROSS_REMOTE=1 cross run --target x86_64-unknown-linux-gnu
Error: No such container:path: cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108467900:\mnt\z\cross\mnt\c\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu\lib
Error: No such container:path: cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-bebb3-1666108467900:\mnt\z\cross\mnt\c\Users\ahusz\.rustup\toolchains
OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/mnt/z/hello") set in config.json failed: no such file or directory: unknown
# on the C: drive
$ CROSS_REMOTE=1 cross run --target x86_64-unknown-linux-gnu
Error: No such container:path: cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-602ca-1666108613311:\mnt\c\cross\mnt\c\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu\lib
Error: No such container:path: cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-602ca-1666108613311:\mnt\c\cross\mnt\c\Users\ahusz\.rustup\toolchains
OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/mnt/c/Users/ahusz/git/hello") set in config.json failed: no such file or directory: unknown
```

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Closes #1081.

### CODE REVIEW

File: src/docker/remote.rs [hunk 1]
```diff
@@ -34,33 +34,50 @@ fn subcommand_or_exit(engine: &Engine, cmd: &str) -> Result<Command> {
     Ok(engine.subcommand(cmd))
 }
 
+fn posix_parent(path: &str) -> Option<&str> {
```
Comment (Alexhuszagh) [inline src/docker/remote.rs:37]: This might need a minor FIXME: `"/".rsplit_once('/')` is `Some(("", ""))`, while `Path::new("/").parent()` is `None`. It doesn't matter here, but should be done.

Comment (Alexhuszagh) [reply src/docker/remote.rs:37]: It might be safer to just change this function to:

 ```rust
pub fn posix_parent_path(path: &str) -> Option<&str> {
    std::path::Path::new(path).parent()?.to_str()
}
```

Since that way any nuances (I don't expect any) are properly handled and we're using Rust's tested tooling.

File: src/docker/remote.rs [hunk 2]
```diff
@@ -34,33 +34,50 @@ fn subcommand_or_exit(engine: &Engine, cmd: &str) -> Result<Command> {
...
+    // on windows, this should be something like `mnt/c`.
+    // that is, all paths inside the container should not have
+    // the mount prefix.
+
+    fn create_dir(
+        &self,
+        reldir: &str,
+        mount_prefix: &str,
+        msg_info: &mut MessageInfo,
+    ) -> Result<ExitStatus> {
```
Comment (Emilgardis) [inline src/docker/remote.rs:52]: there is no argument called `path`, this should also probably be a `# Notes` in a doc-comment

**Review by Emilgardis — APPROVED** [review]
nice :D, just a minor change and should be good

File: src/docker/remote.rs (hunk 2 above)
Comment (Alexhuszagh) [reply src/docker/remote.rs]: Does this look better? I've made them just regular comments since none of the private methods are doc comments, but I can convert them if desired.

**Review by Emilgardis — APPROVED** [review]
bors r+
