### PR TITLE
Fix linkage and C++ support for musl targets.

### LINKED ISSUE #902: `x86_64-unknown-linux-musl` links to Glibc With C++ Dependencies
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

**UPDATE**: All targets except `x86_64-unknown-linux-musl` have been patched as of #905, and the MIPS64 targets in #906.

When compiling for some musl targets, they link to dynamically to glibc rather than musl libc statically. This only occurs with C++ dependencies.  A simple test is as follows:

```bash
$ git clone https://github.com/cross-rs/rust-cpp-hello-word
$ cd rust-cpp-hello-word
$ cross build --target aarch64-unknown-linux-musl
   Compiling cc v1.0.73
   Compiling hellopp v0.1.0 (/home/ahuszagh/Desktop/cross/rust-cpp-hello-word)
    Finished dev [unoptimized + debuginfo] target(s) in 2.58s

$ file target/aarch64-unknown-linux-musl/debug/hellopp
target/aarch64-unknown-linux-musl/debug/hellopp: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, with debug_info, not stripped
```

Some targets, such as `armv7-unknown-linux-musleabihf` link properly, however, while running, they cannot find the correct dynamic library loader.

This is related to #101, although not exactly.

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-musl

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [x] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [x] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2 (latest main)

### Example

_No response_

### Additional information / notes

_No response_

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Change behavior to use static-pie linkage by default (consistent with Alpine's behavior for pure Rust packages as well as those with external C dependencies), and fix musl targets with C++ dependencies by forcing static-pie linkage to standard libraries.

Closes #902.

### CODE REVIEW

**Comment by Emilgardis** [comment]
bors try --target *musl* --cpp 1

**Comment by Alexhuszagh** [comment]
This changes the default linkage, and will increase the executable size of the generated binaries (but only for C++ binaries), but ensure maximum portability and allow libraries with C++ dependencies to build and run correctly.

The following sizes exist:

| Package Type | Original | Original (Stripped) | New | New (Stripped) |
|:-:|:-:|:-:|:-:|:-:|
| Rust | 3.9M | 396K | 3.9M | 396K |
| C | 3.9M | 392K | 3.9M | 392K | 
| C++ | 4.2M | 492K | 14M | 892K |

File: docker/musl.sh [hunk 1]
```diff
@@ -36,13 +36,33 @@ main() {
...
+    export CFLAGS="-fPIC -fPIE ${CFLAGS}"
+    export CXXFLAGS="-fPIC -fPIE ${CXXFLAGS}"
+    set -u
+    # we need to enable `-fPIE` or to avoid relocations in libstdc++
+    # we also don't want dynamic linking to the standard libraries
+    # enable -fPIC just to be safe. alpine GCC is built with
+    # `--enable-default-pie`, so we want to ensure we use that.
+    # `--disable-shared` is required to avoid the issues with linking
+    # to the wrong standard library, which causes a segfault. you can
+    # rust itself disables shared libraries with musl:
```
[the remark this answers is not in the document]
Comment (Alexhuszagh) [reply docker/musl.sh:51]: My mistake. It originally had something about cc-rs, which ignores the shared flag, but I removed this since it was irrelevant.

File: docker/musl.sh [hunk 2]
```diff
@@ -36,13 +36,33 @@ main() {
     # Don't depend on the mirrors of sabotage linux that musl-cross-make uses.
     local linux_headers_site=https://ci-mirrors.rust-lang.org/rustc/sabotage-linux-tarballs
 
+    # we need -fPIC for CFLAGS because old binutils versions
+    # don't understand debug symbols for more recent builds
+    set +u
+    export CFLAGS="-fPIC -fPIE ${CFLAGS}"
```
Comment (Alexhuszagh) [inline docker/musl.sh:42]: The `-fPIE` here is probably unneeded, as is `CXXFLAGS`, but it's done just out of an abundance of precaution.

**Comment by Alexhuszagh** [comment]
The `mips-unknown-linux-musl` and `mipsel-unknown-linux-musl` failures in CI confuse me, since `crt_static_respected: true` for [linux](https://github.com/rust-lang/rust/blob/2d3a85b4f8ba7e2554f4d4fee126bc2ac6ee2af4/compiler/rustc_target/src/spec/linux_base.rs#L13), `base.crt_static_default = true;` for the [32-bit mips targets](https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/linux_musl_base.rs#L13) and I don't believe they're supposed to link anywhere to [libgcc_s](https://github.com/rust-lang/rust/blob/4c5665583815a0f0f3e22516441efb43ea6dede2/compiler/rustc_target/src/spec/crt_objects.rs#L66-L86). This seems to be a known issue https://github.com/rust-lang/rust/issues/82521. That being said, we can probably get around this by just by symlinking our `libgcc.a` to `libgcc_s.a`.

```
error: linking with `mips-linux-muslsf-gcc` failed: exit status: 1
Error:   |
  = note: "mips-linux-muslsf-gcc" "/tmp/rustcUH2otM/symbols.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.hello.fccae6e0-cgu.0.rcgu.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.hello.fccae6e0-cgu.1.rcgu.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.hello.fccae6e0-cgu.2.rcgu.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.hello.fccae6e0-cgu.3.rcgu.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.hello.fccae6e0-cgu.4.rcgu.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.hello.fccae6e0-cgu.5.rcgu.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.hello.fccae6e0-cgu.6.rcgu.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.hello.fccae6e0-cgu.7.rcgu.o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9.3lna4hjplgiexh2x.rcgu.o" "-Wl,--as-needed" "-L" "/target/mips-unknown-linux-musl/debug/deps" "-L" "/target/debug/deps" "-L" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libstd-d6d67ab280b6c06a.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libpanic_unwind-d27f360bda44297f.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libobject-4ca0eb31a10e71f4.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libmemchr-fcabdc871c5d6f00.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libaddr2line-ea9c884ef3d4e1c7.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libgimli-b9cd8f9115c89d02.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/librustc_demangle-9d508ef7308138c6.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libstd_detect-c2e22da431dbb0f4.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libhashbrown-277d58d205da90dd.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libminiz_oxide-db11edea7ebc97c1.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libadler-831b50189349c89c.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/librustc_std_workspace_alloc-b0d3bdee69724baa.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libunwind-8393a96e77e3a073.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libcfg_if-711b760cf48f8ee6.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/liblibc-7af5383540ab9b65.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/liballoc-8a6fceb722872fdf.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/librustc_std_workspace_core-54eead1a7c1070c7.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libcore-4ed9f6d0735ec78a.rlib" "-Wl,--end-group" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib/libcompiler_builtins-d8ca1f65dd356df9.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/mips-unknown-linux-musl/lib" "-o" "/target/mips-unknown-linux-musl/debug/deps/hello-6820248237858af9" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/local/bin/../lib/gcc/mips-linux-muslsf/9.2.0/../../../../mips-linux-muslsf/bin/ld: cannot find -lgcc_s
          collect2: error: ld returned 1 exit status
```

**Comment by Alexhuszagh** [comment]
bors try --target mips*musl --cpp 1

**Comment by Alexhuszagh** [comment]
Changing this to a draft since it breaks if `-C target-feature=-crt-static` is enabled. There might be a better way to do this.

File: docker/musl.sh (hunk 2 above)
Comment (Alexhuszagh) [reply docker/musl.sh]: This is no longer be needed since we no longer add `-disable-shared` to our config.

**Comment by Alexhuszagh** [comment]
bors try --target mips*musl --cpp 1

File: ci/test.sh [hunk 3]
```diff
@@ -182,6 +182,21 @@ main() {
 
         rm -rf "${td}"
     fi
+
+    # special tests for a shared C runtime, since we disable the shared c++ runtime
```
Comment (Alexhuszagh) [inline ci/test.sh:186]: This doesn't need a check for C++ support since it's for a shared C runtime. The C++ runtime will always be static, and we've tested that above.

File: docker/musl.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (Alexhuszagh) [reply docker/musl.sh]: We don't need this anymore since we no longer disable shared libraries.

**Review by Emilgardis — APPROVED** [review]
bors r+
