### PR TITLE
fix path issue

### LINKED ISSUE #993: when pre-building custom docker image inside docker container cross uses weird path
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When building with `CROSS_CONTAINER_IN_CONTAINER=true` pre-building uses weird path e.g.:

```
docker build --label 'org.cross-rs.for-cross-target=aarch64-unknown-linux-gnu' --label 'org.cross-rs.workspace_root=/mount/core' --tag cross-custom-core:aarch64-unknown-linux-gnu-2ed18-pre-build --build-arg 'CROSS_CMD=dpkg --add-architecture arm64 && apt-get update && apt-get install -y libc6:arm64 openssl libudev-dev:arm64 pkg-config-aarch64-linux-gnu && alias pkg-config=aarch64-linux-gnu-pkg-config' --build-arg 'CROSS_DEB_ARCH=arm64' --file /mount/core/target/aarch64-unknown-linux-gnu/Dockerfile.aarch64-unknown-linux-gnu-custom /run/desktop/mnt/host/d/repos/work/core`
```

While `CROSS_CONTAINER_IN_CONTAINER=false` would avoid this problem using file system inside docker as it is, in my case it is `/mount/core`, but it makes me unable to build due to missing `cargo`, not sure why exactly:

```
sh: 1: cargo: not found
```

The way I start docker image:

```
docker run --rm --network host --name docker-desktop -v <my repo>:/mount -v //var/run/docker.sock:/var/run/docker.sock --privileged -it <image name>
```

It seems it only happens because I mounted this directory, but this is honestly not good idea.
It should use mounted folder, not trying to pick source by inspecting docker contaier and checking the mount

It is probably not going to be a problem inside github actions where I intend to use it, but this is basically unusable when I do local test

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [X] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (4645d93 2022-07-10)

### Example

_No response_

### Additional information / notes

_No response_

### PR DESCRIPTION
**Pull request by Emilgardis**
fixes #993 

```
+ /usr/local/bin/docker buildx build --label 'org.cross-rs.for-cross-target=aarch64-unknown-linux-gnu' --label 'org.cross-rs.runs-with=x86_64-unknown-linux-gnu' --label 'org.cross-rs.workspace_root=/tmp/tmp.cmePkb/workspace' --tag localhost/cross-rs/cross-custom-workspace:aarch64-unknown-linux-gnu-e570c-pre-build --build-arg 'CROSS_CMD=exit' --build-arg 'CROSS_DEB_ARCH=arm64' --file /tmp/tmp.cmePkb/workspace/target/aarch64-unknown-linux-gnu/Dockerfile.aarch64-unknown-linux-gnu-custom --output 'type=docker' /var/lib/docker/overlay2/5b7e7f3b1f39b622d2a665281973f5c1bdc2dce21f33c0bc105ceee253cfbe42/merged/tmp/tmp.cmePkb
error: unable to prepare context: path "/var/lib/docker/overlay2/5b7e7f3b1f39b622d2a665281973f5c1bdc2dce21f33c0bc105ceee253cfbe42/merged/tmp/tmp.cmePkb" not found
Error: 
   0: could not run container
   1: when building custom image
   2: when pre-building
   3: `/usr/local/bin/docker buildx build --label 'org.cross-rs.for-cross-target=aarch64-unknown-linux-gnu' --label 'org.cross-rs.runs-with=x86_64-unknown-linux-gnu' --label 'org.cross-rs.workspace_root=/tmp/tmp.cmePkb/workspace' --tag localhost/cross-rs/cross-custom-workspace:aarch64-unknown-linux-gnu-e570c-pre-build --build-arg 'CROSS_CMD=exit' --build-arg 'CROSS_DEB_ARCH=arm64' --file /tmp/tmp.cmePkb/workspace/target/aarch64-unknown-linux-gnu/Dockerfile.aarch64-unknown-linux-gnu-custom --output 'type=docker' /var/lib/docker/overlay2/5b7e7f3b1f39b622d2a665281973f5c1bdc2dce21f33c0bc105ceee253cfbe42/merged/tmp/tmp.cmePkb` failed with exit status: 1
```

this issue presents because the `--file` arg is wrong

### CODE REVIEW

**Comment by Emilgardis** [comment]
bors try --target x86_64-unknown-linux-gnu

**Comment by Emilgardis** [comment]
bors try --target x86_64-unknown-linux-gnu

**Comment by Emilgardis** [comment]
these should fail

bors try --target x86_64-unknown-linux-gnu

**Comment by Emilgardis** [comment]
bors try --target cross

**Comment by Emilgardis** [comment]
bors try --target cross

**Comment by Emilgardis** [comment]
should fail, no fix applied

bors try --target cross

**Comment by Emilgardis** [comment]
bors try --target cross

cross image failed, but for wrong reason

**Comment by Emilgardis** [comment]
bors try --target cross

**Comment by Emilgardis** [comment]
bors try --target cross

**Comment by Emilgardis** [comment]
bors try-

bors try --target cross

**Comment by Emilgardis** [comment]
it failed for the correct reason now!

bors try --target cross

File: ci/test-docker-in-docker.sh [hunk 1]
```diff
@@ -23,8 +23,8 @@ ci_dir=$(realpath "${ci_dir}")
 . "${ci_dir}"/shared.sh
 
 main() {
-    docker run -v "${PROJECT_HOME}":"${PROJECT_HOME}" -w "${PROJECT_HOME}" \
-        --rm -e TARGET -e RUSTFLAGS -e RUST_TEST_THREADS \
+    docker run --platform linux/amd64 -v "${PROJECT_HOME}":"${PROJECT_HOME}" -w "${PROJECT_HOME}" \
```
Comment (Emilgardis) [inline ci/test-docker-in-docker.sh:26]: added this as a bonus, not really needed but I had to add it to run on my arm64

File: src/docker/shared.rs [hunk 2]
```diff
@@ -261,7 +261,7 @@ pub struct Directories {
 impl Directories {
     pub fn create(
         mount_finder: &MountFinder,
-        metadata: &CargoMetadata,
+        metadata: &mut CargoMetadata,
```
Comment (Emilgardis) [inline src/docker/shared.rs:264]: to ensure that further path references are correct, we specify this as `&mut`

File: src/docker/shared.rs [hunk 3]
```diff
@@ -335,7 +335,7 @@ impl Directories {
         Ok(Directories {
             cargo,
             xargo,
-            target,
+            target: metadata.target_directory.clone(),
```
Comment (Emilgardis) [inline src/docker/shared.rs:338]: ideally, we'd not have this here, but sometimes we use `Directories`, sometimes we use `CargoMetadata`, ideally we'd only use one `CargoMetadata`

**Review by Emilgardis — COMMENTED** [review]
this should be good to go

File: ci/test-docker-in-docker.sh (hunk 1 above)
Comment (Alexhuszagh) [reply ci/test-docker-in-docker.sh:26]: I think this is great for consistency, since we might not be deploying ARM64 images for a while and until #982 is merged, only `linux/amd64` will work anyway.

File: src/docker/shared.rs (hunk 2 above)
Comment (Alexhuszagh) [reply src/docker/shared.rs:264]: Not sure I like this design: we should probably either:
1. Factor this out into 2 functions (one to find the mount path of the target directory and one for `Directories::create`)
2. Rename the function so it's clear it modifies `CargoMetadata`.

**Review by Alexhuszagh — CHANGES_REQUESTED** [review]
`Directories::create` with the mount finder changes needs to be refactored into 2 functions, or the function needs to be renamed. Something that is supposed to create a new struct shouldn't modify one of its arguments.

**Comment by Alexhuszagh** [comment]
Nice change with `create` to `assemble`.

bors r+

**Review by Alexhuszagh — APPROVED** [review]
bors r+
