### PR TITLE
Fix persistent data volumes with remote cross.

### LINKED ISSUE #1016: `CROSS_REMOTE=1` with persistent volume doesn't change project files
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Using `CROSS_REMOTE=1` with persistent volume, changing files in the project does not carry over across the first remote build.

### What target(s) are you cross-compiling for?

_No response_

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

8d8d84b

### Example

```
$ cross-util volumes create
$ cargo new --bin issue1016
$ cd issue1016
$ CROSS_REMOTE=1 cross run
...
   Compiling issue1008 v0.1.0 (/cross/Users/emil/workspace/issue1016)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `/linux-runner x86_64 target/x86_64-unknown-linux-gnu/debug/issue1016`
Hello, world!
$ # edit src/main.rs to say something else
$ CROSS_REMOTE=1 cross run
...
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `/linux-runner x86_64 target/x86_64-unknown-linux-gnu/debug/issue1016`
Hello, world!
```

### Additional information / notes

tested in ci in https://github.com/cross-rs/cross/runs/8285127194?check_suite_focus=true

### PR DESCRIPTION
**Pull request by Alexhuszagh**
This fixes copying files into a directory inside a docker data volume, where previously we copied the entire temp directory into the volume itself. This meant that `tmp.tmpLkX8M3` would be copied to `"${volume}/tmp.tmpLkX8M3"`, rather than its contents being copied into `"${volume}"`. This also contains numerous other bugs fixes and changes internally, which have been submitted each as separate commits.

This fixes a regression in #1054 to re-enable fingerprinting to work, since previously the fingerprint file name was based off the container name. Since #1054 changes the container names to rely on the system time, this ensures the fingerprints are specific for only the toolchain and the path of directory.

This also simplifies the internals of the docker module substantially. Most free functions have been modified to become methods of structs to simplify their function signatures. Some structs have also been renamed to make it clearer what their purpose is.

Closes #1016.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
I still need a few things to do:
- [ ] Structify the `Engine`

File: src/docker/remote.rs [hunk 1]
```diff
@@ -561,7 +564,7 @@ impl QualifiedToolchain {
             .file_name()
             .expect("should be able to get toolchain name")
             .to_utf8()?;
-        let toolchain_hash = path_hash(self.get_sysroot())?;
+        let toolchain_hash = path_hash(self.get_sysroot(), 5)?;
```
Comment (Emilgardis) [inline src/docker/remote.rs:570]: could we make the path static variables?

File: src/bin/commands/containers.rs [hunk 2]
```diff
@@ -441,7 +441,7 @@ pub fn create_persistent_volume(
     }
     // store first, since failing to non-existing container is fine
     docker::ChildContainer::create(engine.clone(), container_id.clone())?;
-    docker.run_and_get_status(msg_info, false)?;
+    docker.run_and_get_status(msg_info, true)?;
```
Comment (Emilgardis) [inline src/bin/commands/containers.rs:445]: nice, I've been annoyed by this :3

File: src/docker/remote.rs [hunk 3]
```diff
@@ -92,7 +92,9 @@ impl<'a, 'b, 'c> ContainerDataVolume<'a, 'b, 'c> {
             file::create_dir_all(dst_path.parent().expect("must have parent"))?;
             fs::copy(&src_path, &dst_path)?;
         }
-        self.copy_files(temppath, dst, msg_info)
+        // if copying from a src directory to dst directory with docker, to
+        // copy the contents from `src` into `dst`, `src` must end with `/.`
+        self.copy_files(&temppath.join("."), dst, msg_info)
```
Comment (Emilgardis) [inline src/docker/remote.rs:97]: should this maybe be checked and done in `copy_files` ?

i.e the functions does it automagically for you

**Review by Emilgardis — CHANGES_REQUESTED** [review]
great!

File: src/docker/remote.rs (hunk 1 above)
Comment (Alexhuszagh) [reply src/docker/remote.rs:570]: Sure. I was going to add a comment on the PR that I made the existing ones all 5, but for the mount identifier, I made it require 10 hexdigits. 

For the old hashes, since they either are for the toolchain path (very few actual paths, especially with rustup), a unique ID for the container (which is unique because of the system time, so a small hash is fine), the package path (which is also prefixed by the package name, so small number of possibilities in real cases), 16^5 or ~1million is plenty unique. 

But we run into a birthday problem pretty fast (we're using SHA1 so it's all trusted data) if we consider a user mounting many directories or a large number of users mounting a non-trivial number of directories each. If we have 16^5 options, asuming everything is perfectly distributed, that means we have a 50% chance of collision at ~1200 directories. If we up that to 10 hexdigits, then we have no issue.

We shouldn't modify the toolchain ID, since it would mean existing data volumes would no longer be used, and there's no reason to modify them. But for arbitrary volume mounts, it's probably a good idea to ensure there's no accidental collision.

File: src/docker/remote.rs (hunk 3 above)
Comment (Alexhuszagh) [reply src/docker/remote.rs:97]: I'll have to check: it's quite possible `copy_cargo` or `copy_rust` relies on this, but it would be trivial to change it to copy-in rather than just copy the entire directory. But this might also need patching elsewhere (looking at `copy_files_nocache`).

Comment (Alexhuszagh) [reply src/docker/remote.rs:97]: So we can't do this entirely (see `rust_base`, where we want to copy into the folder), but we can do it for `copy_files_nocache`, so everything for the project files should be quite doable.

```rust
        let dst = mount_prefix.join(&dirs.sysroot_mount_path_relative()?);
        let rustlib = Path::new("lib").join("rustlib");
        self.create_dir(&dst.join(&rustlib), msg_info)?;
        for basename in ["bin", "libexec", "etc"] {
            let file = dirs.get_sysroot().join(basename);
            self.copy_files(&file, &dst, msg_info)?;
        }
```

See here, we want to copy `bin`, `libexec`, `etc` into `rustlib`, so to `rustlib/bin`, etc.

File: src/docker/remote.rs (hunk 1 above)
Comment (Alexhuszagh) [reply src/docker/remote.rs]: I've added the following global const variables, so it's clear why we're using each in a given scenario.

```rust
/// Short hash for identifiers with minimal risk of collision.
pub const PATH_HASH_SHORT: usize = 5;

/// Longer hash to minimize risk of random collisions
/// Collision chance is ~10^-6
pub const PATH_HASH_UNIQUE: usize = 10;
```

**Review by Emilgardis — APPROVED** [review]
lgtm!

bors r+
