### PR TITLE
Fix mount paths on Windows.

### LINKED ISSUE #1145: CI Tests Can Fail on Windows
Currently, we get the CI tests using the following:

```bash
export CROSS="${PROJECT_HOME}/target/debug/cross"
```

This works fine as long as the project has not been built out of the same directory on Windows and WSL2. However, if both `cross` and `cross.exe` exist, this will fail. The solution is, ideally, to append `.exe` if the host is Windows.

### LINKED ISSUE #1156: Issue Mounting and Using Workspaces in Git Bash/CMD on Windows
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When using docker or podman on a Windows machine (run from Git bash or CMD, likely also Powershell), the container engine fails to change directories to the mounted project directory. Although the mount directories for the same locations are properly mounted, the `-w` flag fails. This is an issue if using `/mnt/c` or `C:\` for the provided path. The attempted workdir attempted to be found relative to Git bash.

On CMD, the workpath is properly found, so the CMD, and CMD is properly mounted, however other issues still seem to exist, since it produces the same error.

None of these issues manifest with `cargo` directly.

The simplest example is to do:

```bash
$ git clone https://github.com/cross-rs/test-workspace
$ cd test-workspace/workspace
$ crossbuild --target x

Oddly, this does not fail with the following invocation:

```bash
$ cross build --target x86_64-unknown-linux-gnu -v --manifest-path="./workspace/Cargo.toml" --workspace
```

### What target(s) are you cross-compiling for?

_No response_

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [X] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [X] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (b238b21 2022-10-12)

### Example

Note that this also reproduces on Windows CMD as well as Git bash, so it's not exclusively a Git bash problem.

```bash
$ /c/Users/ahusz/git/cross/target/debug/cross.exe build --target x86_64-unknown-linux-gnu --workspace -v
+ cargo metadata --format-version 1 --filter-platform x86_64-unknown-linux-gnu
+ rustc --print sysroot
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe"
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" version -f '{{ .Server.Os }},,,{{ .Server.Arch }}'
+ rustup toolchain list
+ rustup target list --toolchain stable-x86_64-unknown-linux-gnu
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
+ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/mnt/c/Users/ahusz/.xargo' -e 'CARGO_HOME=/mnt/c/Users/ahusz/.cargo' -e 'CROSS_RUST_SYSROOT=/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e TERM -e 'USER=ahusz' -e 'CROSS_RUSTC_MAJOR_VERSION=1' -e 'CROSS_RUSTC_MINOR_VERSION=64' -e 'CROSS_RUSTC_PATCH_VERSION=0' -v 'C:\Users\ahusz\git\cross\target\tmp\tmp.5z26cWTEes\external\external_lib:/mnt/c/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/external/external_lib:z' --name cross-stable-x86_64-unknown-linux-gnu-9de56-a55dd71d5-x86_64-unknown-linux-gnu-12695-1669472749478 --rm --user 1000:1000 -v 'C:\Users\ahusz\.xargo:/mnt/c/Users/ahusz/.xargo:z' -v 'C:\Users\ahusz\.cargo:/mnt/c/Users/ahusz/.cargo:z' -v /mnt/c/Users/ahusz/.cargo/bin -v 'C:\Users\ahusz\git\cross\target\tmp\tmp.5z26cWTEes\workspace:/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace:z' -v 'C:\Users\ahusz\.rustup\toolchains\stable-x86_64-unknown-linux-gnu:/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:z,ro' -v 'C:\Users\ahusz\git\cross\target\tmp\tmp.5z26cWTEes\workspace\target:/target:z' -w /mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace -t ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main sh -c 'PATH="$PATH":"/mnt/c/Users/ahusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin" cargo build --target x86_64-unknown-linux-gnu --workspace -v'
error: failed to load manifest for workspace member `/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace/binary`

Caused by:
  failed to load manifest for dependency `test-workspace`

Caused by:
  failed to load manifest for dependency `external_lib`

Caused by:
  failed to read `/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/external/external_lib/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
```

Note that running the following works:

```bash
$ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" run --userns host \
    -v 'C:\Users\ahusz\git\cross\target\tmp\tmp.5z26cWTEes\external\external_lib:/mnt/c/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/external/external_lib:z' \
    -it ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main bash
$  ls /mnt/c/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/external/external_lib
Cargo.toml  src
```

As does:

```bash
$ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" run --userns host \
    -v 'C:\Users\ahusz\git\cross\target\tmp\tmp.5z26cWTEes\workspace:/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace:z' \
    -it ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main bash
$  ls /mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace/binary/
Cargo.toml  src
```

So clearly, the issue extends a bit past just the basic error messages reported. However, the failing step is:

```bash
$ "C:\Program Files\Docker\Docker\resources\bin\docker.exe" run --userns host \
    -v 'C:\Users\ahusz\git\cross\target\tmp\tmp.5z26cWTEes\workspace:/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace:z' \
    -w '/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace' \
    -it ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main bash
docker: Error response from daemon: the working directory 'C:/Program Files/Git/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace' is invalid, it needs to be an absolute path.
See 'docker run --help'.
```

Meanwhile, a similar issue occurs when using Podman:

```bash
$ podman run --userns host     -v 'C:\Users\ahusz\git\cross\target\tmp\tmp.5z26cWTEes\workspace:/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace:z'     -w '/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace'     -it ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main bash
Error: error preparing container f2ad9a0ac2a0aa6666f69ea52311f7cef253d8e489bcff6909cad98152d2bac7 for attach: workdir "C:/Program Files/Git/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace" does not exist on container f2ad9a0ac2a0aa6666f69ea52311f7cef253d8e489bcff6909cad98152d2bac7
```

However, when using CMD, the above command works perfectly fine:

```bash
> docker run --userns host -v "C:\Users\ahusz\git\cross\target\tmp\tmp.5z26cWTEes\workspace:/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace:z"  -w "/mnt/c/Users/ahusz/git/cross/target/tmp/tmp.5z26cWTEes/workspace"  -it ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main bash
$ exit
```

### Additional information / notes

Presumably this also affects other engines, such as lima.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Fixes mount paths outside of the workspace mount directory on Windows and those provided as a WSL path. This also adds unittests for Windows outside of WSL2.

Closes #1145.
Closes #1156.

### CODE REVIEW

File: ci/test-remote.sh [hunk 1]
```diff
@@ -20,7 +20,8 @@ main() {
 
     retry cargo fetch
     cargo build
-    export CROSS="${PROJECT_HOME}/target/debug/cross"
+    CROSS=$(cross_bin "${PROJECT_HOME}" debug)
+    export CROSS
     export CROSS_UTIL="${PROJECT_HOME}/target/debug/cross-util"
```
Comment (Alexhuszagh) [inline ci/test-remote.sh:25]: This could use something similar to `cross_bin`. We could likely generalize here.

File: src/docker/local.rs [hunk 2]
```diff
@@ -13,6 +13,7 @@ use eyre::Context;
 // NOTE: host path must be absolute
 fn mount(docker: &mut Command, host_path: &Path, absolute_path: &Path, prefix: &str) -> Result<()> {
     let mount_path = absolute_path.as_posix_absolute()?;
+    // TODO(ahuszagh) mount_path needs to be fixed
```
Comment (Alexhuszagh) [inline src/docker/local.rs:16]: Whoops.

**Comment by Alexhuszagh** [comment]
I forgot about this:
https://github.com/cross-rs/cross/actions/runs/3554788542/jobs/5971093867#step:5:258

**Comment by Alexhuszagh** [comment]
I recommend testing this locally on Windows using `ci/test.sh` just to confirm it works. I've added unittests but just we should ensure we have slightly more comprehensive coverage prior to merging.

File: ci/shared.sh [hunk 3]
```diff
@@ -48,3 +48,20 @@ function mkcargotemp {
...
 }
+
+function binary_path() {
+    local binary="${1}"
+    local home="${2}"
+    local build_mode="${3}"
+    local cross="${home}/target/${build_mode}/${binary}"
+
+    case "$OSTYPE" in
+        msys*|cygwin*)
```
Comment (Alexhuszagh) [inline ci/shared.sh:59]: Git Bash uses `msys` for the `OSTYPE`, while Cygwin of course uses `cygwin`, and MSYS2 uses `msys`.

File: src/file.rs [hunk 4]
```diff
@@ -34,7 +34,7 @@ pub trait PathExt {
 #[cfg(target_family = "windows")]
 fn format_prefix(prefix: &str) -> Result<String> {
     match prefix {
-        "" => eyre::bail!("Error: got empty windows prefix"),
+        "" => Ok("".to_owned()),
```
Comment (Alexhuszagh) [inline src/file.rs:37]: Turns out, this can actually happen if `/mnt/c` is provided to `absolute_path`.

File: src/file.rs [hunk 5]
```diff
@@ -196,13 +196,27 @@ fn _canonicalize(path: &Path) -> Result<PathBuf> {
     }
 }
 
+fn is_wsl_absolute(path: &str) -> bool {
+    if !cfg!(target_os = "windows") {
+        return false;
+    }
+    let path = path.strip_prefix("/mnt/").unwrap_or(path);
+
```
Comment (Alexhuszagh) [inline src/file.rs:204]: Maybe we should remove this extra line.

File: ci/test.sh [hunk 6]
```diff
@@ -31,7 +31,9 @@ main() {
     export QEMU_STRACE=1
 
     # ensure we have the proper toolchain and optional rust flags
-    export CROSS=("${PROJECT_HOME}/target/debug/cross")
+    local cross_path
+    cross_path=$(binary_path cross "${PROJECT_HOME}" debug)
+    export CROSS=("${cross_path}")
```
Comment (Emilgardis) [inline ci/test.sh:36]: why the intermediary variable?

File: src/file.rs [hunk 7]
```diff
@@ -196,13 +196,27 @@ fn _canonicalize(path: &Path) -> Result<PathBuf> {
...
 // Fix for issue #581. target_dir must be absolute.
 pub fn absolute_path(path: impl AsRef<Path>) -> Result<PathBuf> {
-    Ok(if path.as_ref().is_absolute() {
-        path.as_ref().to_path_buf()
-    } else {
-        env::current_dir()?.join(path)
-    })
+    let as_ref = path.as_ref();
+    Ok(
+        if as_ref.is_absolute() || is_wsl_absolute(as_ref.to_utf8()?) {
```
Comment (Emilgardis) [inline src/file.rs:214]: `is_wsl_absolute` should probably only be called on a system with `wsl`

```suggestion
        if as_ref.is_absolute() || cfg!(target_family = "windows") && is_wsl_absolute(as_ref.to_utf8()?) {
```

**Review by Emilgardis — CHANGES_REQUESTED** [review]

File: src/file.rs (hunk 7 above)
Comment (Alexhuszagh) [reply src/file.rs:214]: We don't currently support any Windows systems without WSL2 thought.

File: ci/test.sh (hunk 6 above)
Comment (Alexhuszagh) [reply ci/test.sh:36]: Ah this was originally due to changes in using it for both `cross` and `cross-util`, which I quickly realized made absolutely no sense.

Comment (Emilgardis) [reply ci/test.sh]: this needs to be changed in other places as well where this was added 👍🏼

Comment (Alexhuszagh) [reply ci/test.sh]: I believe it was changed everywhere, as that was the only instance of it.

**Review by Emilgardis — APPROVED** [review]
bors r+

nice!

**Comment by Alexhuszagh** [comment]
bors retry
