### PR TITLE
Convert --target-dir to use absolute paths.

### LINKED ISSUE #581: `--target-dir` results in `failed to create directory /target/release`
Cross is running docker with `--user`, and when you use `--target-dir` it adds a volume mount from the directory to `/target`, like so:

```bash
docker run <...> -v mytargetdir:/target:Z <...>
```

The `/target` directory will be owned by root, and cross will fail to create anything there.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Converts relative target directories to absolute paths, to avoid creating the target directory in the sysroot. This keeps the prior behavior if the provided target directory is an absolute path.

Fixes #581.

### CODE REVIEW

File: src/cli.rs [hunk 1]
```diff
@@ -15,7 +16,16 @@ pub struct Args {
     pub docker_in_docker: bool,
 }
 
-pub fn parse(target_list: &TargetList) -> Args {
+// Fix for issue 581. target_dir must be absolute.
```
Comment (Emilgardis) [inline src/cli.rs:19]:
```suggestion
// Fix for issue #581. target_dir must be absolute.
```

**Review by Emilgardis — CHANGES_REQUESTED** [review]

**Review by Emilgardis — APPROVED** [review]
bors r+
