### PR TITLE
Change `mips64-unknown-linux-gnuabi64` to hard-float.

### LINKED ISSUE #906: MIPS64 Musl Targets Assume Hard-Float but Fail with Hard-Float Toolchain
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When compiling with external dependencies for MIPS64 (MIPS64 or MIPS64EL), the musl targets assume hard-floats, but the actual targets should used soft-floats.

The target spec shows:

```text
$ rustc +nightly --print target-features -Z unstable-options --target mips64-unknown-linux-muslabi64
Features supported by rustc for this target:
    fp64                     - Support 64-bit FP registers.
    msa                      - Mips MSA ASE.
    crt-static               - Enables C Run-time Libraries to be statically linked.

Code-generation features supported by LLVM for this target:
...
    nomadd4                  - Disable 4-operand madd.fmt and related instructions.
    nooddspreg               - Disable odd numbered single-precision registers.
    p5600                    - The P5600 Processor.
    ptr64                    - Pointers are 64-bit wide.
    single-float             - Only supports single precision float.
    soft-float               - Does not support floating point instructions.
    sym32                    - Symbols are 32 bit on Mips64.
...
```

### What target(s) are you cross-compiling for?

mips64el-unknown-linux-muslabi64, mips64-unknown-linux-muslabi64

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2

### Example

A sample project with the following C-dependency and Rust binary will fail to compile:

**sf.c**

```c
float truncate(float start)
{
    float first = __trunctfsf2((long double) start);
    return (float)first;
}
```

**main.rs**

```rust
fn main() {
    let truncated = unsafe {
        truncate(50.0)
    };
    println!("truncated={:?}", truncated);
}

extern "C" {
    fn truncate(_: f32) -> f32;
}
```

However, attempting to build the project causes the following error message:

```text
  = note: /usr/local/bin/../lib/gcc/mips64-linux-muslsf/9.2.0/../../../../mips64-linux-muslsf/bin/ld: warning: /target/mips64-unknown-linux-muslabi64/debug/deps/hellopp-c76d728dba2f1a1d uses -mhard-float (set by /rust/lib/rustlib/mips64-unknown-linux-muslabi64/lib/self-contained/crt1.o), /target/mips64-unknown-linux-muslabi64/debug/build/hellopp-749888b7d3fb49a8/out/libhello.a(hello.o) uses -msoft-float
```

### Additional information / notes

This is related to https://github.com/rust-lang/rust/issues/50890.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Changes `mips64-unknown-linux-gnuabi64` to use a hard-float musl toolchain, rather than a soft-float one.

Closes #906.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
Still a draft because I'm attempting to build a fully static musl toolchain, since there's linker errors if the `-lgcc` is not provided, but this causes a symbol dependency on `/usr/lib64/libc.so.1`. This is based off of the comment [here](https://github.com/richfelker/musl-cross-make/issues/64#issuecomment-497881830). This is due to an undefined reference to `__trunctfsf2@@GCC_3.0` in strtod, needed for `iostream`, which is unusual since this is a soft-float routine. Providing it however allows the binaries to run.

File: docker/mips64-linux-muslabi64-gcc.sh [hunk 1]
```diff
@@ -0,0 +1,18 @@
+#!/bin/bash
+
+# this fixes an issue of missing symbols from the command lines
+# these soft-float routines are required even for hard-float targets.
+#   (strtod.lo): undefined reference to symbol '__trunctfsf2@@GCC_3.0'
```
Comment (Emilgardis) [inline docker/mips64-linux-muslabi64-gcc.sh:5]: Should we ln this exec to make sure it's executed? Is that maybe not really needed (since cwd _shouldn't_ change)

Comment (Alexhuszagh) [reply docker/mips64-linux-muslabi64-gcc.sh:5]: The `cwd` won't change from where the script is invoked, so I don't think this is an issue.

**Comment by Alexhuszagh** [comment]
bors try --target mips64-unknown-linux-gnuabi64

**Comment by Alexhuszagh** [comment]
Windows issue, for some reason the permissions got reset even on Git bash.

**Comment by Alexhuszagh** [comment]
bors r=Emilgardis

**Comment by Alexhuszagh** [comment]
Currently waiting on #978.
bors r-

**Comment by Alexhuszagh** [comment]
bors retry

**Comment by Alexhuszagh** [comment]
bors r=Emilgardis
