### PR TITLE
Fix docker detection.

### LINKED ISSUE #530: Failure when podman-docker is installed
If one has `podman-docker` installed (a wrapper for podman that emulates docker's CLI, needed for things like docker-compose to be compatible), cross fails:
```
cross build --release --target=aarch64-unknown-linux-gnu

Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
error: failed to open: /target/release/.cargo-lock

Caused by:
  Permission denied (os error 13)
```

It looks like cross is trying to use docker, but since my user doesn't have access to "docker" (the emulated interface) it fails. 

Without `podman-docker`, everything works perfectly fine using rootless podman containers.

Cross should probably either default to trying podman first and then falling back to docker, or have some sort of check so this doesn't happen.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Currently, docker detection fails under a few cases:
1. If `podman_docker` is installed, so the filename is docker but the actual executable is podman.
2. If the executable has a suffix, such as `.exe` on Windows, because we check if the executable `ends_with(DOCKER)`.

The only reliable way to fix both these issues, IE, if the actual engine is docker and not an alias, and if the executable does not contain a suffix, is to query the container engine. This might not be ideal for performance reasons, but is the only reliable way to fix these issues.

Closes #530.
Closes #538.

### CODE REVIEW

File: src/docker.rs [hunk 1]
```diff
@@ -126,6 +136,7 @@ pub fn run(
     let runner = config.runner(target)?;
 
     let mut docker = docker_command("run")?;
+    let is_docker = get_is_docker(get_container_engine().unwrap(), verbose)?;
```
Comment (Alexhuszagh) [inline src/docker.rs:139]: Note that this can't fail due to the above command: `docker_command` ensures that `get_container_engine` is not an error.

**Review by Emilgardis — APPROVED** [review]
bors r+
