### PR TITLE
Fix tag names for custom docker images.

### LINKED ISSUE #894: Invalid Docker Tags in Custom Docker Images
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Currently, if a project directory (inadvisably) contains invalid characters for a Docker tag, this will cause a build with pre-build hooks or a custom Dockerfile to fail.

A working example available [here](https://github.com/Alexhuszagh/CrossPrebuildUppercase).

This produces the following errors:

```bash
$  cross build --target x86_64-unknown-linux-gnu --verbose
+ cargo metadata --format-version 1 --filter-platform x86_64-unknown-linux-gnu
+ rustc --print sysroot
+ rustup toolchain list
+ rustup target list --toolchain stable-x86_64-unknown-linux-gnu
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
+ /usr/bin/docker
+ "/home/ahuszagh/git/CrossPrebuildUppercase" /usr/bin/docker build --label 'org.cross-rs.for-cross-target=x86_64-unknown-linux-gnu' --label 'org.cross-rs.workspace_root=/home/ahuszagh/git/CrossPrebuildUppercase' --tag cross-custom-CrossPrebuildUppercase:x86_64-unknown-linux-gnu-d59ad-pre-build --build-arg 'CROSS_CMD=apt-get update' --build-arg 'CROSS_DEB_ARCH=amd64' --file /home/ahuszagh/git/CrossPrebuildUppercase/target/x86_64-unknown-linux-gnu/Dockerfile.x86_64-unknown-linux-gnu-custom .
invalid argument "cross-custom-CrossPrebuildUppercase:x86_64-unknown-linux-gnu-d59ad-pre-build" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.
Error: 
   0: could not run container
   1: when building custom image
   2: when pre-building
   3: `/usr/bin/docker build --label 'org.cross-rs.for-cross-target=x86_64-unknown-linux-gnu' --label 'org.cross-rs.workspace_root=/home/ahuszagh/git/CrossPrebuildUppercase' --tag cross-custom-CrossPrebuildUppercase:x86_64-unknown-linux-gnu-d59ad-pre-build --build-arg 'CROSS_CMD=apt-get update' --build-arg 'CROSS_DEB_ARCH=amd64' --file /home/ahuszagh/git/CrossPrebuildUppercase/target/x86_64-unknown-linux-gnu/Dockerfile.x86_64-unknown-linux-gnu-custom .` failed with exit status: 125

Note: CROSS_CMD=apt-get update
```

### What target(s) are you cross-compiling for?

_No response_

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [x] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2 (latest main)

### Example

_No response_

### Additional information / notes

_No response_

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Ensures the filenames in custom docker image tags are valid docker tag
characters. This requires the following:
- lowercase ASCII letters
- digits
- a period
- 1-2 underscores
- 1 or more hyphens (dashes)

Closes #894.

### CODE REVIEW

File: src/docker/custom.rs [hunk 1]
```diff
@@ -138,3 +134,86 @@ impl<'a> Dockerfile<'a> {
...
+
+fn docker_tag_name(file_name: &str) -> String {
+    // a valid image name consists of the following:
+    // - lowercase ASCII letters
+    // - digits
+    // - a period
+    // - 1-2 underscores
+    // - 1 or more hyphens (dashes)
+    let mut result = String::new();
+    let mut consecutive_underscores = 0;
```
Comment (Alexhuszagh) [inline src/docker/custom.rs:162]: This needs to track state to ensure we don't have more than 2 consecutive underscores, or else this would be a lot easier/idiomatic.

Comment (Emilgardis) [reply src/docker/custom.rs:162]: why not just remove any consecutive underscore?

```rs
name.to_ascii_lowercase().replace("__", "_").chars().filter(|c| c.is_ascii_digit() | matches!(c, '-' | '_'))
```

Comment (Emilgardis) [reply src/docker/custom.rs:162]: reverse the order of the replace? so raplce after filtering

Comment (Alexhuszagh) [reply src/docker/custom.rs:162]: I still don't think that works, since it doesn't match a pattern. We'd need a regex. For example:

```rust
# produces `package___test_name`, which is invalid
# we want `package_test_name` or `package__test_name`.
docker_tag_name("pAcKaGe_____test_name")  
```

Sine we can have 6, 7, or more ones, we'd have to do an iterative replace, which sounds like a bad idea.

**Review by Emilgardis — APPROVED** [review]
