### PR TITLE
Various bug fixes for cross.

### LINKED ISSUE #901: Docker-in-Docker fails with Mounted Volumes in Workspaces
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When running docker-in-docker, if using a workspace and not at the root directory, the mounted volumes in the workspace are not properly adjusted to the the mounted prefix. This is because `docker_mount` does not use the mount finder.

### What target(s) are you cross-compiling for?

_No response_

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2 (00c1de2)

### Example

While testing the integration tests in #873, the following script fails, producing the subsequent output:

**Script**

```bash
#!/usr/bin/env bash

# test to see that running docker-in-docker works

set -x
set -eo pipefail

if [[ -z "${TARGET}" ]]; then
    export TARGET="aarch64-unknown-linux-gnu"
fi

source=$(dirname "${BASH_SOURCE[0]}")
source=$(realpath "${source}")
home=$(dirname "${source}")

main() {
    docker run -v "${home}":/project \
        -w /project --rm -e TARGET \
        -v /var/run/docker.sock:/var/run/docker.sock \
        docker:18.09-dind sh -c '
#!/usr/bin/env sh
set -x
set -euo pipefail

apk add curl
curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "${HOME}/.cargo/env"

# building on release is slow
apk add libgcc gcc musl-dev
cargo test --workspace
cargo install --path . --force --debug

export CROSS_CONTAINER_IN_CONTAINER=1

apk add git
td="$(mktemp -d)"
git clone --depth 1 https://github.com/cross-rs/rust-cpp-hello-word "${td}"
cd "${td}"
cross run --target "${TARGET}" --verbose

td="$(mktemp -d)"
git clone --depth 1 https://github.com/cross-rs/test-workspace "${td}"
cd "${td}"
cross build --target "${TARGET}" --workspace \
    --manifest-path="./workspace/Cargo.toml" --verbose
cd workspace
cross build --target "${TARGET}" --workspace --verbose
cd binary
cross run --target "${TARGET}" --verbose
'
}

main
```

**Output**

```
/usr/local/bin/docker run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/xargo' -e 'CARGO_HOME=/cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e 'USER=root' -v /tmp/tmp.hppfjI/external/external_lib:/tmp/tmp.hppfjI/external/external_lib --rm --user 0:0 -v /var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/root/.xargo:/xargo:Z -v /var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/root/.cargo:/cargo:Z -v /cargo/bin -v /var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/tmp/tmp.hppfjI/workspace:/var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/tmp/tmp.hppfjI/workspace:Z -v /var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/rust:Z,ro -v /var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/tmp/tmp.hppfjI/workspace/target:/target:Z -w /var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/tmp/tmp.hppfjI/workspace ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.2 sh -c 'PATH=$PATH:/rust/bin cargo build --target aarch64-unknown-linux-gnu --workspace --verbose'
error: failed to load manifest for workspace member `/var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/tmp/tmp.hppfjI/workspace/binary`

Caused by:
  failed to load manifest for dependency `test-workspace`

Caused by:
  failed to load manifest for dependency `external_lib`

Caused by:
  failed to read `/var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/tmp/tmp.hppfjI/external/external_lib/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

We can see that `external_lib` is mounted at `/tmp/tmp.hppfjI/external/external_lib:/tmp/tmp.hppfjI/external/external_lib `, and not at `/var/lib/docker/overlay2/4f20476a48228131897c42ce45df9e9ef74864fc590040ebfa4bce7f086f375e/merged/tmp/tmp.hppfjI/test-workspace/external/external_lib/`. Likewise, we only mount `workspace`, and not `test-workspace`.

### Additional information / notes

_No response_

### LINKED ISSUE #903: Some RUSTFLAGS Force Cargo Use on the Host
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Attempting to run the following causes `cross` to assume that we do not need docker support, and therefore fallback to the host:

```bash
$ CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-Zsanitizer=leak" \
    cross +nightly build --target aarch64-unknown-linux-gnu -Z build-std -vv
+ cargo metadata --format-version 1 --filter-platform aarch64-unknown-linux-gnu                                                                                                                     
Warning: Falling back to `cargo` on the host.                                                                                                                                                       
+ cargo +nightly build --target aarch64-unknown-linux-gnu -Z build-std -vv                                                                                                                          
   Compiling compiler_builtins v0.1.73
```

I believe this affects every image. Not every rustflag however affects this: only unstable `-Z` flags are affected. For example, this works:

```bash
$  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-C panic=abort" \
    cross +nightly build --target aarch64-unknown-linux-gnu -Z build-std -vv
```

Note that this does not occur when using `cross rustc` and passing the options: the following works as expected:

```bash
$ cross +nightly rustc --target x86_64-unknown-linux-gnu -- -Zself-profile -Zsanitizer=leak
```

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2  and latest main

### Example

_No response_

### Additional information / notes

This affected cross prior to #869 being merged, so this is not related to that.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Fixed `cargo metadata` failing with unstable arguments in rustflags if the default toolchain was not nightly. We also log any warnings that occurred if we cannot get metadata. Also fixed a lack of formatting in messages with remote docker support. The mount paths are also correctly processed if using docker-in-docker for mounted volumes.

Closes #901.
Closes #903.
Required for #873.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
I've confirmed this works on:
1. x86_64-pc-windows-msvc (Windows host, not WSL2)
2. x86_64-unknown-linux-gnu (Linux host, host not in Docker)
3. x86_64-unknown-linux-gnu (Linux host, Docker in Docker)
4. x86_64-unknown-linux-gnu (Windows host, WSL2)

File: src/docker/shared.rs [hunk 1]
```diff
@@ -647,6 +648,23 @@ impl MountFinder {
...
+            // On Windows, we can not mount the directory name directly. Instead, we use wslpath to convert the path to a linux compatible path.
+            if host {
+                return Ok(path.to_utf8()?.to_string());
+            } else {
+                return path.as_wslpath();
+            }
+        }
+        #[cfg(not(target_os = "windows"))]
+        {
+            return Ok(self.find_mount_path(path).to_utf8()?.to_string());
```
Comment (Emilgardis) [inline src/docker/shared.rs:665]: I think, just for future-proofing, we should make cross fail if `CONTAINER_IN_CONTAINER` is enabled and `os = windows`. I don't think that scenario will happen but it blocks it as we know it wont work

Comment (Alexhuszagh) [reply src/docker/shared.rs:665]: I've added a check at the start of the docker command to fail if running on Windows and in docker:

https://github.com/cross-rs/cross/pull/904/files#diff-7f0024537bbf8484f3e68ec502bd9cff7805e1f6eaee0eb072647a14e1bdb36fR31-R37

**Review by Emilgardis — APPROVED** [review]
bors r+
